export const CHANGE_ACTIVE_ITEM = 'CHANGE_ACTIVE_ITEM';
export const FETCH_MERCHLIST = 'FETCH_MERCHLIST';
export const POST_NEW_ITEM = 'POST_NEW_ITEM';
export const FETCH_FILTERLIST = 'FETCH_FILTERLIST';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const PURCHASE_ITEM = 'PURCHASE_ITEM';